// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {connection} from '../models';
import {main} from '../models';

export function CreateConnection(arg1:connection.Connection,arg2:string,arg3:string):Promise<connection.Connection>;

export function DeleteConnection(arg1:string):Promise<void>;

export function GetConnections():Promise<Array<connection.Connection>>;

export function GetPlatform():Promise<string>;

export function GetSettings():Promise<main.UserPreferences>;

export function GetSettingsPath():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SaveSettings(arg1:main.UserPreferences):Promise<void>;

export function TestConnection(arg1:connection.Connection,arg2:string,arg3:string):Promise<string>;

export function UpdateConnection(arg1:connection.Connection,arg2:string,arg3:string):Promise<connection.Connection>;

export function UpdateMenu(arg1:string):Promise<void>;
