// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConnections():Promise<Array<main.ConnectionProfile>>;

export function GetPlatform():Promise<string>;

export function GetSettings():Promise<main.UserPreferences>;

export function GetSettingsPath():Promise<string>;

export function GetStoragePath():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SaveSettings(arg1:main.UserPreferences):Promise<void>;

export function UpdateMenu(arg1:string):Promise<void>;
