// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConnections():Promise<Array<main.ConnectionProfile>>;

export function GetStoragePath():Promise<string>;

export function Greet(arg1:string):Promise<string>;
