// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateConnection'](arg1, arg2, arg3);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSettingsPath() {
  return window['go']['main']['App']['GetSettingsPath']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function TestConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2, arg3);
}

export function UpdateConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateConnection'](arg1, arg2, arg3);
}

export function UpdateMenu(arg1) {
  return window['go']['main']['App']['UpdateMenu'](arg1);
}
