// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetStoragePath() {
  return window['go']['main']['App']['GetStoragePath']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
