// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['connection']['ConnectionService']['Connect'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['connection']['ConnectionService']['DeleteProfile'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['connection']['ConnectionService']['Disconnect'](arg1);
}

export function ExecuteQuery(arg1, arg2) {
  return window['go']['connection']['ConnectionService']['ExecuteQuery'](arg1, arg2);
}

export function GetActiveSessions() {
  return window['go']['connection']['ConnectionService']['GetActiveSessions']();
}

export function GetColumns(arg1, arg2, arg3) {
  return window['go']['connection']['ConnectionService']['GetColumns'](arg1, arg2, arg3);
}

export function GetProfiles() {
  return window['go']['connection']['ConnectionService']['GetProfiles']();
}

export function GetSchemas(arg1) {
  return window['go']['connection']['ConnectionService']['GetSchemas'](arg1);
}

export function GetTables(arg1, arg2) {
  return window['go']['connection']['ConnectionService']['GetTables'](arg1, arg2);
}

export function SaveProfile(arg1, arg2) {
  return window['go']['connection']['ConnectionService']['SaveProfile'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['connection']['ConnectionService']['Startup'](arg1);
}

export function TestConnection(arg1, arg2) {
  return window['go']['connection']['ConnectionService']['TestConnection'](arg1, arg2);
}
