// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {connection} from '../models';
import {context} from '../models';

export function CancelQuery(arg1:string):Promise<void>;

export function Connect(arg1:string):Promise<string>;

export function DeleteProfile(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function ExecuteQuery(arg1:string,arg2:string,arg3:number):Promise<connection.QueryResult>;

export function GetActiveSessions():Promise<Array<connection.SessionSummary>>;

export function GetColumns(arg1:string,arg2:string,arg3:string):Promise<Array<connection.TableColumn>>;

export function GetProfiles():Promise<Array<connection.Connection>>;

export function GetSchemas(arg1:string):Promise<Array<string>>;

export function GetTables(arg1:string,arg2:string):Promise<Array<connection.DatabaseTable>>;

export function SaveProfile(arg1:connection.Connection,arg2:string):Promise<connection.Connection>;

export function Startup(arg1:context.Context):Promise<void>;

export function TestConnection(arg1:connection.Connection,arg2:string):Promise<string>;
